version: "3"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "46876:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: src/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env

    depends_on:
      - db
    ports:
      - "46877:8080"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${POSTGRES_ADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
  #   ports:
  #     # - "23439:80"
  #   volumes:
  #     - ./docker/pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - db

volumes:
  pgdata:
    # external: true
